#!/bin/bash
./spl spl_progs/stage23/exception.spl
./spl spl_progs/stage23/int-console.spl
./spl spl_progs/stage23/int-disk.spl
./spl spl_progs/stage23/int-timer.spl
./spl spl_progs/stage23/int4-file.spl
./spl spl_progs/stage23/int6-read.spl
./spl spl_progs/stage23/int7-write.spl
./spl spl_progs/stage23/int8-fork.spl
./spl spl_progs/stage23/int9-exec.spl
./spl spl_progs/stage23/int10-halt.spl
./spl spl_progs/stage23/int11-wait-signal.spl
./spl spl_progs/stage23/int13-sem-get-rel.spl
./spl spl_progs/stage23/int14-sem-lock-unlock.spl
./spl spl_progs/stage23/int15-shutdown.spl
./spl spl_progs/stage23/mod0-resource.spl
./spl spl_progs/stage23/mod1-process.spl
./spl spl_progs/stage23/mod2-memory.spl
./spl spl_progs/stage23/mod4-device.spl
./spl spl_progs/stage23/mod5-scheduler.spl
./spl spl_progs/stage23/mod7-boot.spl
./spl spl_progs/stage23/startup.spl
