#!/bin/bash
./spl spl_progs/stage27/exception.spl
./spl spl_progs/stage27/int-console.spl
./spl spl_progs/stage27/int-disk.spl
./spl spl_progs/stage27/int-timer.spl
./spl spl_progs/stage27/int4-file.spl
./spl spl_progs/stage27/int5-open-close.spl
./spl spl_progs/stage27/int6-read.spl
./spl spl_progs/stage27/int7-write.spl
./spl spl_progs/stage27/int8-fork.spl
./spl spl_progs/stage27/int9-exec.spl
./spl spl_progs/stage27/int10-halt.spl
./spl spl_progs/stage27/int11-wait-signal.spl
./spl spl_progs/stage27/int12-logout.spl
./spl spl_progs/stage27/int13-sem-get-rel.spl
./spl spl_progs/stage27/int14-sem-lock-unlock.spl
./spl spl_progs/stage27/int15-shutdown.spl
./spl spl_progs/stage27/int16-uid-pass.spl
./spl spl_progs/stage27/int17-login.spl
./spl spl_progs/stage27/mod0-resource.spl
./spl spl_progs/stage27/mod1-process.spl
./spl spl_progs/stage27/mod2-memory.spl
./spl spl_progs/stage27/mod3-file.spl
./spl spl_progs/stage27/mod4-device.spl
./spl spl_progs/stage27/mod5-scheduler.spl
./spl spl_progs/stage27/mod6-pager.spl
./spl spl_progs/stage27/mod7-boot.spl
./spl spl_progs/stage27/startup.spl
