#!/bin/bash
./spl spl_progs/stage22/exception.spl
./spl spl_progs/stage22/int-console.spl
./spl spl_progs/stage22/int-disk.spl
./spl spl_progs/stage22/int-timer.spl
./spl spl_progs/stage22/int6-read.spl
./spl spl_progs/stage22/int7-write.spl
./spl spl_progs/stage22/int8-fork.spl
./spl spl_progs/stage22/int9-exec.spl
./spl spl_progs/stage22/int10-halt.spl
./spl spl_progs/stage22/int11-wait-signal.spl
./spl spl_progs/stage22/int13-sem-get-rel.spl
./spl spl_progs/stage22/int14-sem-lock-unlock.spl
./spl spl_progs/stage22/int15-shutdown.spl
./spl spl_progs/stage22/mod0-resource.spl
./spl spl_progs/stage22/mod1-process.spl
./spl spl_progs/stage22/mod2-memory.spl
./spl spl_progs/stage22/mod4-device.spl
./spl spl_progs/stage22/mod5-scheduler.spl
./spl spl_progs/stage22/mod7-boot.spl
./spl spl_progs/stage22/startup.spl
