#!/bin/bash
./spl spl_progs/stage21/exception.spl
./spl spl_progs/stage21/int-console.spl
./spl spl_progs/stage21/int-disk.spl
./spl spl_progs/stage21/int-timer.spl
./spl spl_progs/stage21/int6-read.spl
./spl spl_progs/stage21/int7-write.spl
./spl spl_progs/stage21/int8-fork.spl
./spl spl_progs/stage21/int9-exec.spl
./spl spl_progs/stage21/int10-halt.spl
./spl spl_progs/stage21/int11-wait-signal.spl
./spl spl_progs/stage21/int15-shutdown.spl
./spl spl_progs/stage21/int15-shutdown.spl
./spl spl_progs/stage21/mod0-resource.spl
./spl spl_progs/stage21/mod1-process.spl
./spl spl_progs/stage21/mod2-memory.spl
./spl spl_progs/stage21/mod4-device.spl
./spl spl_progs/stage21/mod5-scheduler.spl
./spl spl_progs/stage21/mod7-boot.spl
./spl spl_progs/stage21/startup.spl
