#!/bin/bash
./spl spl_progs/stage25/exception.spl
./spl spl_progs/stage25/int-console.spl
./spl spl_progs/stage25/int-disk.spl
./spl spl_progs/stage25/int-timer.spl
./spl spl_progs/stage25/int4-file.spl
./spl spl_progs/stage25/int5-open-close.spl
./spl spl_progs/stage25/int6-read.spl
./spl spl_progs/stage25/int7-write.spl
./spl spl_progs/stage25/int8-fork.spl
./spl spl_progs/stage25/int9-exec.spl
./spl spl_progs/stage25/int10-halt.spl
./spl spl_progs/stage25/int11-wait-signal.spl
./spl spl_progs/stage25/int13-sem-get-rel.spl
./spl spl_progs/stage25/int14-sem-lock-unlock.spl
./spl spl_progs/stage25/int15-shutdown.spl
./spl spl_progs/stage25/mod0-resource.spl
./spl spl_progs/stage25/mod1-process.spl
./spl spl_progs/stage25/mod2-memory.spl
./spl spl_progs/stage25/mod3-file.spl
./spl spl_progs/stage25/mod4-device.spl
./spl spl_progs/stage25/mod5-scheduler.spl
./spl spl_progs/stage25/mod7-boot.spl
./spl spl_progs/stage25/startup.spl
