#!/bin/bash
./spl spl_progs/stage24/exception.spl
./spl spl_progs/stage24/int-console.spl
./spl spl_progs/stage24/int-disk.spl
./spl spl_progs/stage24/int-timer.spl
./spl spl_progs/stage24/int4-file.spl
./spl spl_progs/stage24/int5-open-close.spl
./spl spl_progs/stage24/int6-read.spl
./spl spl_progs/stage24/int7-write.spl
./spl spl_progs/stage24/int8-fork.spl
./spl spl_progs/stage24/int9-exec.spl
./spl spl_progs/stage24/int10-halt.spl
./spl spl_progs/stage24/int11-wait-signal.spl
./spl spl_progs/stage24/int13-sem-get-rel.spl
./spl spl_progs/stage24/int14-sem-lock-unlock.spl
./spl spl_progs/stage24/int15-shutdown.spl
./spl spl_progs/stage24/mod0-resource.spl
./spl spl_progs/stage24/mod1-process.spl
./spl spl_progs/stage24/mod2-memory.spl
./spl spl_progs/stage24/mod3-file.spl
./spl spl_progs/stage24/mod4-device.spl
./spl spl_progs/stage24/mod5-scheduler.spl
./spl spl_progs/stage24/mod7-boot.spl
./spl spl_progs/stage24/startup.spl
